header_index:
    path:     /
    defaults: { _controller: "AppBundle:Header:index" }
    methods:  GET

header_show_all:
    path:     /admin/show_all
    defaults: { _controller: "AppBundle:Header:allHeader" }
    methods:  GET

header_new:
    path:     /admin/new
    defaults: { _controller: "AppBundle:Header:new" }
    methods:  [GET, POST]

header_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "AppBundle:Header:edit" }
    methods:  [GET, POST]

header_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "AppBundle:Header:delete" }
    methods:  DELETE
