movies_index:
    path:     /admin/index
    defaults: { _controller: "AppBundle:Movies:index" }
    methods:  GET

movies_list:
    path:     /list
    defaults: { _controller: "AppBundle:Movies:list" }
    methods:  GET

movies_show:
    path:     /admin/{id}/show
    defaults: { _controller: "AppBundle:Movies:show" }
    methods:  GET

movies_new:
    path:     /admin/new
    defaults: { _controller: "AppBundle:Movies:new" }
    methods:  [GET, POST]

movies_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "AppBundle:Movies:edit" }
    methods:  [GET, POST]

movies_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "AppBundle:Movies:delete" }
    methods:  DELETE
