year_index:
    path:     /
    defaults: { _controller: "AppBundle:Year:index" }
    methods:  GET

year_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Year:show" }
    methods:  GET

year_new:
    path:     /new
    defaults: { _controller: "AppBundle:Year:new" }
    methods:  [GET, POST]

year_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Year:edit" }
    methods:  [GET, POST]

year_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Year:delete" }
    methods:  DELETE
