AppBundle\Entity\Media:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        picname:
            type: string
            length: 255
            nullable: false
        picpath:
            type: string
            length: 255
            nullable: false
    lifecycleCallbacks: {  }
