AppBundle\Entity\Resume:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ResumeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        resume:
            type: text
            nullable: true
        author:
            type: string
            length: 255
            nullable: true
        actors:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }
